# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-09-29 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20150929_2214'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('tree_id', 'name')]),
        ),
    ]
